### ISSUE TITLE
broken on firefox

### ISSUE THREAD

**Issue by denniszl** [prestonp/got-em#14]
<img width="1440" alt="screen shot 2016-04-07 at 1 26 40 pm" src="https://cloud.githubusercontent.com/assets/6801949/14362302/77075f2e-fcc4-11e5-9922-9f32f7de0d61.png">

**Comment by davidmenendez** [comment]
fixed with https://github.com/prestonp/got-em/pull/30

Firefox has no voice support, so now we check to see if the browser has voice support. If it doesn't the speech code is never run and we hide the speech elements on the page. The regular sound functionality will still work in Firefox.
