### ISSUE TITLE
Add a link to the GitHub page to report issues

### ISSUE THREAD

**Issue by JanekLehr** [prestonp/got-em#41]
Maybe in some "About" page

**Comment by jroyal** [comment]
The usual stuff on the bottom of a webpage

**Comment by prestonp** [comment]
<img width="1004" alt="screen shot 2017-01-22 at 9 23 19 pm" src="https://cloud.githubusercontent.com/assets/1265379/22190476/0c8ed2bc-e0e9-11e6-80b0-8d79bd7e1046.png">
